---
- name: Copy yarn.gpg to the server
  copy:
    src: yarn.gpg
    dest: /tmp/yarn.gpg

- name: Add yarn repo key
  apt_key:
    file: /tmp/yarn.gpg
    state: present

- name: Add yarn repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - apache2
      - python-pymysql
      - yarn
      - python3-virtualenv
      - python3-setuptools
      - python3-distutils
      - build-essential

# really need systemd from testing, because otherwise the python deps from testing will BREAK
# systemd from stable
- name: Install required packages from testing
  apt:
    default_release: testing
    state: latest
    name:
      - python3.7
      - python3.7-dev
      - libapache2-mod-wsgi-py3
      - systemd
      - nodejs
      - mariadb-server

- name: Get mod_auth_openidc from github releases
  apt:
    deb: "{{ mod_auth_openidc_url  }}"

- name: Enable mod_auth_openidc
  apache2_module:
    state: present
    name: "{{item}}"
  with_items:
    - auth_openidc
    - rewrite

- name: Remove stable python 3 version
  apt:
    autoremove: yes
    purge: yes

- name: Add SBS database
  mysql_db:
    name: sbs
    encoding: utf8
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Add SBS user
  mysql_user:
    name: sbs
    host: "{{sbs_db_host}}"
    password: "{{ sbs_db_password }}"
    priv: 'sbs.*:ALL'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Clone SBS repository
  git:
    repo: "{{ sbs_repository }}"
    dest: "{{ sbs_git_dir }}"
    version: "{{ sbs_version }}"
    force: yes
  notify: reload Apache
  register: git_apps

- debug:
    var: git_apps

- name: Add git info to server
  shell: git --git-dir {{ sbs_git_dir }}/.git  log -1 > {{ sbs_git_dir }}/server/api/git.info
  changed_when: false

- name: Create python3 virtualenv
  pip:
    virtualenv: "{{ sbs_env_dir }}"
    virtualenv_python: python3
    requirements: "{{ sbs_git_dir }}/server/requirements/test.txt"

- name: Install yarn dependancies
  yarn:
    path: "{{ sbs_git_dir }}/client"
  when:
    - git_apps.changed

- name: Build client yarn
  command: yarn build
  args:
    chdir: "{{ sbs_git_dir }}/client"
    creates: "{{ sbs_git_dir }}/client/build"

- name: Create SBS config file
  template:
    src: config.yml.j2
    dest: "{{ sbs_git_dir }}/server/config/config.yml"

- name: Create SBS wsgi file
  template:
    src: sbs-api.wsgi.j2
    dest: "{{ sbs_git_dir }}/sbs-api.wsgi"

- name: Create SBS environment disclaimer file
  template:
    src: disclaimer.css.j2
    dest: "{{ sbs_git_dir }}/server/static/disclaimer.css"

- name: touch sbs.log file
  file:
    path: /opt/sbs/sbs/log
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: enable Apache modules
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
    - auth_openidc
    - wsgi

- name: Configure Apache vhost
  template:
    src: sbs.conf.j2
    dest: /etc/apache2/sites-enabled/sbs.conf
  notify: restart Apache
