---
- include_vars: comanage_idp.yml

- name: ensure that packages are installed
  apt:
    name: "{{ packages  }}"
    state: present
  become: Yes

- name: Ensure directory exists
  file:
    path: "{{ idp_mellon_path }}"
    state: directory
    owner: www-data
    mode: 0755

- name: Get the IdP metadata
  get_url:
    url: "{{ idp_metadata_url }}"
    dest: "{{ idp_metadata_path }}"
    owner: www-data
    mode: 0600
    force: yes
    validate_certs: no

