---
- name: Copy create_db file
  copy:
    src: "create_db.sql"
    dest: /tmp

- name: create database for CoManage-Proxy linkup
  mysql_db:
    name: "{{ comanage_proxy_db_name }}"
    state: import
    target: /tmp/create_db.sql

- name: create user for mysql with all privilege
  mysql_user:
    name: "{{ comanage_proxy_db_user }}"
    host: "%"
    password: "{{ comanage_proxy_db_password }}"
    priv: "{{ comanage_proxy_db_name }}.*:ALL"
    state: present
  notify:
    - Restart MySQL

- name: Install backup script
  template:
    src: "satosa_mysql_backup.sh.j2"
    dest: "{{backup_runparts}}/satosa_mysql_backup.sh"
    mode: 0755
