---
# Use containers instead of full VMs for faster startup.
sudo: required

services:
  - docker

notifications:
  # default: send to commiter
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: "GwjWmymXdHh3pyaDtriIrGyBqQGpFvS2sCa9yrO5xKrnPh0OZtJdVCNKCYREaSsdMp6NYL6EqoQgzABdl8\
               ErK9VQ7ErpUZMuDKhaPZL4LTZ4CfuSdytD7g58Kmx1JYfLe7wuc3iiZi3XXpklK1TScHDyUFFR24imDXHG\
               f2E/DPSsB6AJGrtqsHtjDE6u6f8XTuq5oEIXGinM50kgzjZamnpgD8Hzms/Jon4wIADy0iabIKaJeNZYsv\
               VgWDP5lckIgRo6YmanTETiUCvOp3NIdcOAjilsEUiJbCAIB/aJ1TaRu3z5R295shgfBpPaz/a47zTCbeeq\
               XMQJ604Mtg4CHRe7S54Fv+whIDGejA3LcEcM4/cxjG3kS3iyXRb6sHMpS7gqUgamjEd2EImcigElsxat4b\
               KkKU13IPNbB4seVDdyXoAIBlkmJTNtzt1vH5DAFU5WHRO+qyOc3YxgX63cYJBcNxFZyZe63UuUSll20/5n\
               jpCBGyVE1YW8rD2iMO/V+HxMY0wQiMyS855q5v9ayi7T5r7oaj98DfXUzzAP8VMKIITAYGiZpQeT5dDO63\
               Ula3eJBTYTcHdpb37KrowB731sox8cBH9A5uAufdgxgUE/c3xo+kBVVLgt13lmBjmMqEdEN6pr8wSueSeI\
               WIdQczg4EOJTLEMVgFBdCmd8f04="

# the syntax check scripts as well as yamllint need python3
language: python
cache: pip
python:
  - 3.5

# disable the default submodule logic, as travis can't reach gitlab anyway
git:
  submodules: false

install:
  - pip install yamllint
  - pip install jinja2
  - sudo wget https://releases.hashicorp.com/vagrant/2.0.3/vagrant_2.0.3_x86_64.deb -P /tmp
  - sudo dpkg -i /tmp/vagrant_2.0.3_x86_64.deb
  #- sudo wget >
  #  https://download.docker.com/linux/ubuntu/dists/trusty/pool/
  #  stable/amd64/docker-ce_18.03.0~ce-0~ubuntu_amd64.deb -P /tmp
  #- sudo dpkg -i /tmp/docker-ce_18.03.0~ce-0~ubuntu_amd64.deb
  #- sudo apt -y update
  - sudo apt -y install software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt -y update
  - sudo apt -y install ansible
  - sudo apt -y install bridge-utils

script:
  - scripts/syntax-check
  - sudo ./start-vm --provider docker
