# vim:ts=2:sw=2:expandtab
---
- hosts: all
  serial: 20
  gather_facts: false
  tasks:
    - name: Read user secrets
      include_vars: "{{ secrets_users_file }}"
      tags: always
    - name: Read vars from secrets file
      include_vars: "{{ secrets_file }}"
      tags: always

# first gather facts from all hosts that we're actually deploying to
- hosts: all
  become: yes
  serial: 20
  gather_facts: true

# to run the debug target, specify --extra-vars="debug=true" / -e debug=1
- hosts: all
  gather_facts: false
  roles:
    - role: debug
      tags: ['debug']
      when: "debug | default('false') | bool"

- hosts: all
  serial: 20
  roles:
    - { role: basic,         tags: ['common']            }
    - { role: apt,           tags: ['common','apt']      }
    - { role: firewall,      tags: ['common','firewall'] }
    - { role: ntp,           tags: ['common']            }
    - { role: users,         tags: ['common','users']    }
    - { role: mail,          tags: ['common','mail']     }
    - { role: syslog-client, tags: ['common','syslog']   }
    - { role: backups,       tags: ['common','backups']  }
    - { role: zabbix-agent,  tags: ['common','zabbix']   }

- hosts: mgnt1
  roles:
    - { role: dns-master,    tags: ['test'] }

- hosts: mgnt2
  roles:
    - { role: syslog-server,   tags: ['syslog'] }

- hosts: lb
  roles:
    - role: http_nginx
      tags: ['lb','http_nginx']
    - role: tls_letsencrypt
      tags: ['lb','tls_letsencrypt']
      when: enable_https and not use_fixed_cert
    - role: tls_fixed_cert
      tags: ['lb','tls_fixedcert']
      when: enable_https and use_fixed_cert
    - { role: https_haproxy,   tags: ['lb','haproxy'] }

- hosts: ldap
  roles:
    - { role: ldap,               tags: ['ldap'                  ] }
    - { role: ldap_clients,       tags: ['ldap', 'ldap-clients'  ] }
    - { role: pam_websso_daemon,  tags: ['client','websso-daemon'] }

- hosts:
    - proxy
    - comanage
  roles:
    - { role: mysql, tags: ['mysql'] }

- hosts: client
  roles:
    - { role: client-base,          tags: ['client','client-base'  ] }
    - { role: client-saml-sp,       tags: ['client','client-sp'    ] }
    - { role: client-saml-idp,      tags: ['client','client-idp'   ] }
    - { role: client-google-idp,    tags: ['client','client-google'] }
    - { role: client-orcid-idp,     tags: ['client','client-orcid' ] }
    - { role: client-microsoft-idp, tags: ['client','client-ms'    ] }
    - { role: client-oidc-rp,       tags: ['client','client-rp'    ] }

- hosts: proxy
  roles:
    - { role: pyff,          tags: ['proxy','pyff'      ] }
    - { role: satosa,        tags: ['proxy','satosa'    ] }
    - { role: cmservice,     tags: ['proxy','cmservice' ] }
    - { role: proxy_mysql,   tags: ['proxy','mysql'     ] }

- hosts: comanage
  roles:
    - { role: http_apache,      tags: ['comanage', 'web'] }
    - { role: comanage_mysql,   tags: ['comanage', 'db' ] }
    - { role: php,              tags: ['comanage', 'web'] }
    - { role: auth_mellon,      tags: ['comanage', 'web'] }
    - { role: comanage,         tags: ['comanage', 'web'] }
    - { role: comanage_idp,     tags: ['comanage', 'web'] }
    - { role: comanage_enable,  tags: ['comanage', 'web'] }
    - { role: comanage_plugins, tags: ['comanage', 'web'] }

- hosts: meta
  roles:
    - { role: http_dummy,  tags: ['meta','http']     }
    - { role: metadata,    tags: ['meta','metadata'] }

- hosts: docker
  roles:
    - { role: sbs,     tags: ['sbs']  }

- hosts: sandbox1
  roles:
    - { role: pam_websso,         tags: ['client','pam-websso'   ] }
