---
# playbook to install and configure general components of the LDAP
- include_vars: "ldap.yml"

- name: Install LDAP
  apt: name={{ item }} state=present
  with_items:
    - slapd
    - unzip
    - ldap-utils

- name: Copying alternative service script
  become: true
  copy:
    src: slapd.service
    dest: /etc/systemd/system
  notify: systemctl daemon-reload
  when: ansible_virtualization_type == "docker"

- name: Ensure that a number of directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ldap_user }}"
    group: "{{ ldap_group }}"
    mode: 0755
  tags: ldap
  with_items:
    - "{{ ldap_bin_dir }}"
    - "{{ ldap_schema_dir }}"
    - "{{ ldap_ldif_dir }}"
    - "{{ ldap_download_dir }}"
    - /var/run/slapd

- name: Enable LDAP
  service: name=slapd state=restarted enabled=yes

- name: Generating password hash for LDAP admin
  command:
    slappasswd -h {SSHA} -s {{ ldap_password }}
  register:
    ldap_root_hash

- name: Copy schema2ldif
  become_user: "{{ ldap_user }}"
  copy:
    src: roles/ldap/files/schema2ldif
    dest: "{{ ldap_bin_dir }}"
    mode: 0755

- name: Generate ldif from template
  become_user: "{{ ldap_user }}"
  become: true
  template:
    src: "{{ item.src }}"
    dest: "{{ ldap_ldif_dir }}/{{ item.dest }}"
    mode: 0644
  with_items:
    - { src: "initial_setup.ldif.j2", dest: "initial_setup.ldif" }
    - { src: "set_root_credentials.ldif.j2", dest: "set_root_credentials.ldif" }
    - { src: "set_loglevel_stats.ldif.j2", dest: "set_loglevel_stats.ldif" }
    - { src: "enable_syncprov.ldif.j2", dest: "enable_syncprov.ldif" }

- name: Ensure the ldap admin credentials are set
  command: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f "{{ ldap_ldif_dir }}/set_root_credentials.ldif"
  register: result
  failed_when: "result.rc not in [0,20,68]"
  changed_when: "result.rc not in [20,68]"

- name: Set loglevel to stats
  command: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f "{{ ldap_ldif_dir }}/set_loglevel_stats.ldif"
  register: result
  failed_when: "result.rc not in [0,20,68]"
  changed_when: "result.rc not in [20,68]"

- name: Enable synchronization
  command: ldapmodify -Q -Y EXTERNAL -H ldapi:/// -f "{{ ldap_ldif_dir }}/enable_syncprov.ldif"
  # return code 20 means entry already exists
  register: result
  failed_when: "result.rc not in [0,20,68]"
  changed_when: "result.rc not in [20,68]"

- name: Check for presence of eduPerson ldif
  stat:
    path: "{{ ldap_schema_dir }}/{{ eduPersonSchema_ldif }}"
  register: edupersonstat

- name: Check for presence of LdapPublicKey ldif
  stat:
    path: "{{ ldap_schema_dir }}/{{ ldapPublicKey_ldif }}"
  register: ldappkstat

- name: Check for presence of eduMember ldif
  stat:
    path: "{{ ldap_schema_dir }}/{{ eduMember_ldif }}"
  register: edumemberstat

- name: Fetch the eduPerson schema
  become: true
  get_url:
    owner: "{{ ldap_user }}"
    group: "{{ ldap_user }}"
    url: "{{ eduPersonSchema_url }}"
    dest: "{{ ldap_download_dir }}"
  when:  edupersonstat.stat.exists == False

# Of course the unarchive module should be used here, but the things is,
# it seems broken in 2.2.0, although it should be fixed in 2.1.1. I guess
# porting the fix to 2.2.0 has been forgotten...
- name: Unzipping downloaded schema
  become_user: "{{ ldap_user }}"
  become: true
  command: unzip -o "{{ ldap_download_dir }}/{{ eduPersonSchema_zip }}" -d /tmp
  when: edupersonstat.stat.exists == False

- name: Copy the unpacked ldifs
  become: true
  become_user: "{{ ldap_user }}"
  copy:
    src: /tmp/{{ eduPersonSchema_ldif }}
    dest: "{{ ldap_schema_dir }}/{{ eduPersonSchema_ldif }}"
    remote_src: true
    owner: "{{ ldap_user }}"
    group: "{{ ldap_user }}"
  when: edupersonstat.stat.exists == False

- name: Fetch LdapPublicKey schema
  become: true
  get_url:
    owner: "{{ ldap_user }}"
    group: "{{ ldap_user }}"
    url: "{{ ldapPublicKeySchema_url }}"
    dest: "{{ ldap_schema_dir }}/ {{ ldapPublicKey }}.schema"
  when: ldappkstat.stat.exists == False

- name: Convert LdapPublicKey schema to ldif format
  command: "{{ ldap_bin_dir }}/schema2ldif {{ ldap_schema_dir }}/{{ ldapPublicKey }}.schema"
  become: true
  become_user: "{{ ldap_user }}"
  when: ldappkstat.stat.exists == False

- name: Fetch eduMember schema
  become: true
  get_url:
    owner: "{{ ldap_user }}"
    group: "{{ ldap_user }}"
    url: "{{ eduMemberSchema_url }}"
    dest: "{{ ldap_schema_dir }}/{{ eduMember }}.schema"
  when: edumemberstat.stat.exists == False

- name: Convert eduMember schema to ldif format
  command: "{{ ldap_bin_dir }}/schema2ldif {{ ldap_schema_dir }}/{{ eduMember }}.schema"
  become: true
  become_user: "{{ ldap_user }}"
  when: edumemberstat.stat.exists == False

# OpenLDAP does not like adding exisiting entries again. Only add the
# schema if it has not been added already. This does not yet take care
# of changes in the eduPerson schema.
- name: Check if eduPerson schema is already present
  shell: >
    ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:/// -b 'cn=schema,cn=config' '(cn=*)' dn
    | grep -i 'cn={[0123456789]\+}eduperson,cn=schema,cn=config'
  failed_when: not [0, 1]
  changed_when: false
  register:
    eduPersonSchemaPresent

# Based on the success or failure of copying the eduPerson schema add
# the schema to the ldap database. Copying the same file in the previous
# task, would lead to not registering the edoPersonSchema variable.
- name: Ensure the eduPerson schema is added to LDAP
  become: true
  command: >
    ldapadd -Q -Y EXTERNAL -H ldapi:///
    -f {{ ldap_schema_dir }}/{{ eduPersonSchema_ldif }}
    -D "cn=config" -w "{{ ldap_password }}"
  when: eduPersonSchemaPresent.stdout == ""
  register: result
  failed_when: "result.rc not in [0,20,68]"
  changed_when: "result.rc not in [20,68]"

- name: Check if the ldapPublicKey schema is already present
  shell: >
    ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:/// -b 'cn=schema,cn=config' '(cn=*)' dn
    | grep -i 'cn={[0-9]\+}openssh-lpk-openldap,cn=schema,cn=config'
  failed_when: not [0, 1]
  changed_when: false
  register:
    ldapPublicKeyTask

- name: Ensure the ldapPublicKey schema is added to LDAP
  become: true
  command: >
    ldapadd -Q -Y EXTERNAL -H ldapi:///
    -f "{{ ldap_schema_dir }}/{{ ldapPublicKey_ldif }}"
    -D "cn=config" -w "{{ ldap_password }}"
  when: ldapPublicKeyTask.stdout == ""
  register: result
  failed_when: "result.rc not in [0,20,68]"
  changed_when: "result.rc not in [20,68]"

- name: Check if the eduMember schema is already present
  shell: >
    ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:/// -b 'cn=schema,cn=config' '(cn=*)' dn
    | grep -i 'cn={[0-9]\+}edumember,cn=schema,cn=config'
  failed_when: not [1, 2]
  changed_when: false
  register:
    eduMemberTask

- name: Ensure the eduMember schema is added to LDAP
  become: true
  command: >
    ldapadd -Q -Y EXTERNAL -H ldapi:///
    -f "{{ ldap_schema_dir }}/{{ eduMember_ldif }}"
    -D "cn=config" -w "{{ ldap_password }}"
  when: eduMemberTask.stdout == ""
  register: result
  failed_when: "result.rc not in [0,20,68]"
  changed_when: "result.rc not in [20,68]"

- name: Check if DIT has been created before
  command:
    ldapsearch -Q -LLL -Y EXTERNAL -H ldapi:/// -b "{{ ldap.basedn }}" "(ou=group)" dn
  register: emptyDIT
  failed_when: "emptyDIT.rc not in [0, 32]"
  changed_when: false

- name: Initialize DIT
  command: >
    ldapadd -c -x -D "{{ ldap.binddn }}" -w "{{ ldap_password }}"
    -f "{{ ldap_ldif_dir }}/initial_setup.ldif"
  register: result
  failed_when: "result.rc not in [0,20,68]"
  changed_when: "result.rc not in [20,68]"
  tags: ldap
  when: emptyDIT.stdout == ""

- name: Redirect slapd log to /var/log/slapd.log
  copy:
    src: rsyslog_slapd.conf
    dest: /etc/rsyslog.d/slapd.conf
  notify: restart rsyslog

- name: Install filebeat configuration
  template:
    src: fb_slapd.yml.j2
    dest: /etc/filebeat/conf.d/fb_slap.yml
  notify: restart filebeat

- name: Install backup script
  template:
    src: ldap-backup.sh.j2
    dest: "{{backup_runparts}}/ldap-backup.sh"
    mode: 0755

