---
- name: set up apt repo
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list
    force: yes

- name: set up apt pinning for official packages
  template:
    src: apt_pinning.j2
    dest: /etc/apt/preferences.d/official_packages

- name: Install common tools / clients
  apt:
    update_cache: yes
    state: present
    name:
      - sudo
      - bash
      - zsh
      - vim
      - locales-all
      - curl
      - net-tools
      - git
      - subversion
      - acl
      - bzip2
      - unzip
      - apt-transport-https
      - python-apt

- name: Upgrade packages
  apt:
    upgrade: dist
    cache_valid_time: 86400
    update_cache: yes
  when: "environment_name != 'vm'"

- name: remove unneccessary packages
  apt:
    state: absent
    purge: yes
    name:
      - cloud-init

- name: remove cloud-init network config
  lineinfile:
    path: /etc/network/interfaces
    state: absent
    regexp: '^source '

- name: install VMware clients
  apt:
    state: present
    name:
      - open-vm-tools
      - open-vm-tools-dkms
  when: ansible_virtualization_type == "VMware"

- name: install Qemu clients
  apt:
    state: present
    name:
      - qemu-guest-agent
  when: ansible_virtualization_type == "kvm"

- name: install VirtualBox clients
  apt:
    state: present
    name:
      - virtualbox-guest-dkms
      - virtualbox-guest-utils
  when: ansible_virtualization_type == "virtualbox"

# apt module doesn't support autoremove very well, yet
- name: Remove obsolete packages
  command: "/usr/bin/apt --yes --purge autoremove"
  register: result
  changed_when: "'0 upgraded, 0 newly installed, 0 to remove' not in result.stdout"

