---

- name: Add docker apt key
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    keyserver: hkps://keys.gnupg.net

- name: add docker apt repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian {{ansible_distribution_release}} stable"
    state: present

- name: install docker
  apt:
    name: "{{item}}"
  with_items:
    - docker-ce

- name: install docker-compose
  get_url:
    url: "{{docker_compose_url}}"
    dest: "/usr/local/bin/docker-compose"
    mode: 0755
    checksum: "sha256:{{docker_compose_sha256}}"

- name: create directory for wordpress
  file:
    path: "{{wordpress_dir}}"
    state: directory

- name: install docker compose configuration
  template:
    src: docker-compose.yml.j2
    dest: "{{wordpress_dir}}/docker-compose.yml"

# can't use ansible module because there is no way to install up to date python docker modules
- name: run docker-compose
  command: "docker-compose up --no-start"
  args:
    chdir: "{{wordpress_dir}}"
  register: result
  changed_when: "result.stderr != ''"

- name: install wordpress service file
  template:
    src: wordpress.service.j2
    dest: /etc/systemd/system/wordpress.service
  register: result

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: result.changed

- name: start wordpress
  systemd:
    name: wordpress.service
    state: started
    enabled: yes

