---

- name: create directory {{item}}
  file:
    dest: "{{item}}"
    state: directory
  with_items:
    - "{{wordpress_dir}}"
    - "{{wordpress_dir}}/db-data"
    - "{{wordpress_dir}}/wp-plugins"

- name: install docker configuration {{item}}
  template:
    src: "{{item}}.j2"
    dest: "{{wordpress_dir}}/{{item}}"
  with_items:
    - docker-compose.yml
    - Dockerfile
    - wp-apache.conf

- name: install wordpress shibboleth plugin
  git:
    repo: "https://github.com/michaelryanmcneill/shibboleth.git"
    version: "2.1.1"
    dest: "{{wordpress_dir}}/wp-plugins/shibboleth"

- name: install additional wordpress plugins
  subversion:
    repo: "{{item.svn}}"
    dest: "{{wordpress_dir}}/wp-plugins/{{item.name}}"
  with_items:
    - name: "disable-xml-rpc"
      svn: "https://plugins.svn.wordpress.org/disable-xml-rpc/tags/1.0.1/"
    - name: "disable-json-api"
      svn: "https://plugins.svn.wordpress.org/disable-json-api/tags/1.4.3/"

# TODO: enable the plugins!

# can't use ansible module because there is no way to install up to date python docker modules
- name: run docker-compose
  command: "docker-compose up --no-start"
  args:
    chdir: "{{wordpress_dir}}"
  register: result
  changed_when: "'Build' in result.stderr or 'Create' in result.stderr or 'Pull' in result.stderr"

- debug: var=result

- name: install wordpress service file
  template:
    src: wordpress.service.j2
    dest: /etc/systemd/system/wordpress.service
  register: result

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: result.changed

- name: start wordpress
  systemd:
    name: wordpress.service
    state: started
    enabled: yes

