---
- name: restart rsyslog
  systemd:  name=rsyslog state=restarted
  listen: "restart rsyslog"

- name: start filebeat Service
  systemd: name=filebeat state=restarted enabled=yes daemon_reload=yes
  listen: "restart filebeat"
  when: use_logserver

