---
packages:
  - slapd
  - ldap-utils
  - unzip

eduPersonSchema_ldif: openLdapEduperson-201602DV.ldif
eduPersonSchema_zip: 2xOpenLdapEduPerson-201602.zip
eduPersonSchema_url: >
  https://spaces.internet2.edu/download/attachments/2309/{{ eduPersonSchema_zip }}

ldapPublicKey: "openssh-lpk-openldap"
ldapPublicKey_ldif: "{{ ldapPublicKey }}.ldif"

# avoid Travis yamllint error on line-length....
ldapPKS1: https://raw.githubusercontent.com/AndriiGrytsenko/
ldapPKS2: openssh-ldap-publickey/master/misc/openssh-lpk-openldap.schema
ldapPublicKeySchema_url: "{{ ldapPKS1 }}{{ ldapPKS2 }}"

eduMember: eduMember
eduMember_ldif: "{{ eduMember }}.ldif"
eduMember_host: https://raw.githubusercontent.com
eduMember_path: /Internet2/grouper/master/apacheds-ldappc-schema/src/main/schema/eduMember.schema
eduMemberSchema_url: "{{ eduMember_host }}{{ eduMember_path }}"

voPerson: voPerson
voPerson_ldif: "{{ voPerson }}.ldif"
voPerson_host: https://raw.githubusercontent.com
voPerson_path: /voperson/voperson/master/schema/openldap/voperson.ldif
voPersonLdif_url: "{{ voPerson_host }}{{ voPerson_path }}"
