---
- name: Install required apps
  apt:
    name:
      - sqlite3

- name: create directory {{item}}
  file:
    dest: "{{item}}"
    state: directory
    owner: "www-data"
  with_items:
    - "{{nextcloud_dir}}"
    - "{{nextcloud_dir}}/data"
    - "{{nextcloud_dir}}/custom_apps"
    - "{{nextcloud_dir}}/config"

- name: install docker configuration {{item}}
  copy:
    src: "{{item}}"
    dest: "{{nextcloud_dir}}/{{item}}"
  with_items:
    - docker-compose.yml
    - 000-default.conf

- name: copy nextcloud database
  copy:
    src: "nextcloud.sql"
    dest: "{{nextcloud_dir}}/nextcloud.sql"

- block:
  - name: install nextcloud user_saml plugin
    git:
      repo: "https://github.com/nextcloud/user_saml.git"
      version: "v2.1.0"
      dest: "{{nextcloud_dir}}/custom_apps/user_saml"

  - name: copy nextcloud config
    copy:
      src: "config.php"
      dest: "{{nextcloud_dir}}/config/config.php"

  - name: make data dir a data dir
    file:
      path: "{{nextcloud_dir}}/data/.ocdata"
      state: touch

  - name: remove nextcloud database
    file:
      path: "{{nextcloud_dir}}/data/nextcloud.sqlite.db"
      state: absent

  - name: create nextcloud database
    shell: "cat {{nextcloud_dir}}/nextcloud.sql | sqlite3 {{nextcloud_dir}}/data/nextcloud.sqlite.db"

  become: yes
  become_user: "www-data"

# can't use ansible module because there is no way to install up to date python docker modules
#- name: run docker-compose
  #command: "docker-compose up --no-start"
  #args:
    #chdir: "{{nextcloud_dir}}"
  #register: result
  #changed_when: "'Build' in result.stderr or 'Create' in result.stderr or 'Pull' in result.stderr"

#- debug: var=result

#- name: install nextcloud service file
  #template:
    #src: nextcloud.service.j2
    #dest: /etc/systemd/system/nextcloud.service
  #register: result

#- name: reload systemd
  #systemd:
    #daemon_reload: yes
  #when: result.changed

#- name: start nextcloud
  #systemd:
    #name: nextcloud.service
    #state: started
    #enabled: yes

