---
- name: Install required apps
  apt:
    name:
      - sqlite3
      - python-docker

- name: create directory
  file:
    dest: "{{item}}"
    state: directory
    owner: "www-data"
  with_items:
    - "{{nextcloud_dir}}"
    - "{{nextcloud_dir}}/data"
    - "{{nextcloud_dir}}/custom_apps"
    - "{{nextcloud_dir}}/config"

- name: install docker configuration
  copy:
    src: "{{item}}"
    dest: "{{nextcloud_dir}}/{{item}}"
  with_items:
    - 000-default.conf

- name: create docker configuration
  template:
    src: "{{item}}.j2"
    dest: "{{nextcloud_dir}}/{{item}}"
  with_items:
    - docker-compose.yml
    - config/config.php

- name: copy nextcloud database
  copy:
    src: "nextcloud.sql"
    dest: "{{nextcloud_dir}}/nextcloud.sql"

- block:
  - name: install nextcloud user_saml plugin
    git:
      repo: "https://github.com/nextcloud/user_saml.git"
      version: "{{ nextcloud_user_saml_version }}"
      dest: "{{nextcloud_dir}}/custom_apps/user_saml"
      update: no

  - name: patch user_saml plugin
    patch:
      src: user_saml.patch
      basedir: "{{nextcloud_dir}}/custom_apps/user_saml"
      strip: 1

  - name: make data dir a data dir
    file:
      path: "{{nextcloud_dir}}/data/.ocdata"
      state: touch

  - name: remove nextcloud database
    file:
      path: "{{nextcloud_dir}}/data/nextcloud.sqlite.db"
      state: absent

  - name: create nextcloud database
    shell: "cat {{nextcloud_dir}}/nextcloud.sql | sqlite3 {{nextcloud_dir}}/data/nextcloud.sqlite.db"

  become: yes
  become_user: "www-data"

- name: Enable modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - dav
  notify:
    - restart apache

- name: Pull recent nextcloud image
  docker_image:
    name: nextcloud:latest

- name: run docker-compose
  command: "/usr/local/bin/docker-compose up --no-start"
  args:
    chdir: "{{nextcloud_dir}}"

- name: install nextcloud service file
  template:
    src: nextcloud.service.j2
    dest: /etc/systemd/system/nextcloud.service

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: start nextcloud
  systemd:
    name: nextcloud.service
    state: started
    enabled: yes

