---
ldap_install_dir: /etc/ldap
ldap_ldif_dir: "{{ ldap_install_dir }}/schema"
ldap_schema_dir: "{{ ldap_install_dir }}/schema"
ldap_backup_dir: "{{backup_base}}/ldap"

ldap_user: openldap
ldap_group: openldap

lsc_install_dir: /opt/lsc
lsc_config_dir: "{{ lsc_install_dir }}/config.d"
lsc_backup_dir: "{{backup_base}}/lsc"

client_ldap_dbdir: "/var/lib/ldap/client"

client_ldap:
  basedn: "dc=client,dc=unknown"
  o: "Clients"
  binddn: "cn=admin,dc=client,{{ldap.base_dn}}"

client_ldap_clients:
  - co_name: Example
    ldap_o: LDAP name
    password: secr1t
    uid_start: 10000
    gid_start: 20000
