# if we enable https, we need a http-only nginx to handle acme-verification
# and http redirects
---
- name: enable nginx
  include: nginx.yml
  when: enable_https

- name: disable nginx
  apt: name=nginx state=absent
  when: not enable_https
