---
- include_vars: comanage_plugins.yml

- name: ensure that packages are installed
  apt:
    name: "{{ packages  }}"
    state: present

- name: Activate standard plugins
  file:
    src: "{{ comanage_path }}/app/AvailablePlugin/{{item}}"
    dest: "{{ comanage_path }}/local/Plugin/{{item}}"
    state: link
  with_items:
    - CoServiceToken
    - LdapServiceTokenProvisioner
  register: standard_plugins

- name: Checkout the relevant Git based plugins
  git:
    repo: "{{ item.src }}"
    dest: "{{ comanage_path }}/local/Plugin/{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ comanage_git_plugins }}"
  register: git_plugins

- name: Install configurations
  template:
    src: "{{ item.src }}"
    dest: "{{ comanage_path }}/app/Config/{{ item.dest }}"
  with_items: "{{ comanage_plugin_configurations }}"
  register: plugin_config

- name: Set Database configuration for external Proxy database
  blockinfile:
    path: "{{ comanage_path }}/local/Config/database.php"
    insertafter: "^class"
    marker: '/* {mark} ANSIBLE MANAGED [scz db] */'
    block: |
      public $scz = array(
          'datasource' => 'Database/Mysql',
          'persistent' => false,
          'host'       => '{{ comanage_proxy_db }}',
          'login'      => '{{ comanage_proxy_db_user }}',
          'password'   => '{{ comanage_proxy_db_password }}',
          'database'   => '{{ comanage_proxy_db_name }}',
          'prefix'     => '',
      );
  register: database_config

- name: Update Cake database
  include: cake_refresh.yml
  when: >
    standard_plugins.changed
    or git_plugins.changed
    or plugin_config.changed
    or database_config.changed

- name: Configure JsonLog for ZoneProvisioner
  blockinfile:
    path: "{{ comanage_path }}/local/Config/bootstrap.php"
    create: yes
    follow: yes
    marker: "// {mark} ANSIBLE MANAGED BLOCK"
    block: |
      CakeLog::config('json', array(
        'engine' => 'ZoneProvisioner.JsonLog',
        'types' => array('json_err','json_not'),
        'path' => '{{ comanage_path }}/local/tmp/logs',
      ));

- name: Remove file in incorrect location
  file:
    path: "{{ comanage_path }}/app/local"
    state: absent
