---
- name: Ensure that packages are installed
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - libnss-ldap
    - nscd
    - libpam-python
    - pamtester
    - libxml2-dev
    - libxmlsec1-dev
    - build-essential
    - python-dev
    - python-pip
    - python-openssl
    - python-setuptools
    - python-wheel
    - python-twisted
    - python-openssl
    - python-defusedxml
    - python-isodate

- name: fetch PAM WebSSO from {{ pam_websso.repo_url }}, version {{ pam_websso.repo_version }}
  git:
    repo: "{{ pam_websso.repo_url }}"
    dest: "{{ pam_websso.project_dir }}"
    version: "{{ pam_websso.repo_version }}"
    accept_hostkey: "yes"
    force: "yes"
  register: pam_websso_git

- name: install PAM WebSSO
  pip:
    name: "{{ pam_websso.project_dir }}"
    #state: latest
  when: pam_websso_git.changed

- name: install PAM WebSSO configuration
  template:
    src: "pam-websso.j2"
    dest: "/etc/pam.d/pam-websso"

- name: install PAM WebSSO settings
  template:
    src: "pam_websso.json.j2"
    dest: "{{ pam_websso.project_dir }}/pam_websso.json"

- name: install NSS LDAP settings
  template:
    src: "libnss-ldap.conf.j2"
    dest: "/etc/libnss-ldap.conf"

- name: install NSS LDAP root pwd
  template:
    src: "pam_ldap.secret.j2"
    dest: "/etc/pam_ldap.secret"

- name: Copy PAM mkhomedir conf
  copy:
    src: "mkhomedir"
    dest: "/usr/share/pam-configs"

- name: Add LDAP nsswitch lookup
  replace:
    path: /etc/nsswitch.conf
    regexp: '^(passwd:.*compat)$'
    replace: '\1 ldap'
    backup: yes

- name: Add LDAP nsswitch lookup
  replace:
    path: /etc/nsswitch.conf
    regexp: '^(group:.*compat)$'
    replace: '\1 ldap'
    backup: yes

- name: Install sshd PAM WebSSO module
  replace:
    path: /etc/pam.d/sshd
    regexp: '\n(\n.*\n@include common-auth\n)'
    replace: >-
      \n\nauth sufficient pam_python.so /opt/pam-websso/pam_websso.py\1
    backup: yes

- name: Install sshd mkhomedir module
  replace:
    path: /etc/pam.d/sshd
    regexp: '\n(\n.*\n@include common-session\n)'
    replace: >-
      \n\nsession required pam_mkhomedir.so umask=0022 skel=/etc/skel\1
    backup: yes

- name: Restart nscd server
  service: name=nscd state=restarted
