---
# todo remove this
- name: remove dehydrated
  apt: name=dehydrated state=absent purge=true

- name: remove obsolete config files
  file: dest=/etc/dehydrated state=absent

- name: remove obsolete cronjob
  file: dest=/etc/cron.daily/scz-dehydrated state=absent
### end


- name: install certbot
  apt: name=certbot state=present

- name: write certbot config for all domains
  template: src=certbot.conf.j2 dest=/etc/letsencrypt/cli.ini

- name: create webroot for acme challenges
  file: dest={{letsencrypt.acme_challenge_dir}} state=directory owner=root group=www-data mode=0755

- name: register letsencrypt account
  command: /usr/bin/certbot register
  args:
    creates: '{{certbot.account_dir}}'
  register: result

- name: create or renew certificates
  command: "/usr/bin/certbot certonly --noninteractive --keep-until-expiring \
            --renew-with-new-domains --domains={{item}}"
  register: result
  changed_when: '"Your certificate and chain have been saved" in result.stdout'
  with_items: '{{loadbalancer|map(attribute="hostname")|list}}'

# extra renewal is necessary, because certbot does not run its renew_hook when the
# certificate is first created
- name: renew certificates
  command: '/usr/bin/certbot certonly --noninteractive --force-renewal --domains={{item}}'
  register: result
  changed_when: '"Your certificate and chain have been saved" in result.stdout'
  args:
    creates: '{{certbot.cert_dir}}/{{item}}/{{certbot.all_pem}}'
  with_items: '{{loadbalancer|map(attribute="hostname")|list}}'

