---
- debug: var=item_client

- set_fact: client="{{item_client}}"
- set_fact: lsc_dir="{{lsc_config_dir}}/{{client | replace(' ','_')}}"

# LSC config
- name: "Make sure LSC directory {{lsc_dir}} exists"
  file:
    path: "{{ lsc_dir }}"
    state: directory
    mode: 0755

- name: Link LSC logging config
  file:
    dest: "{{ lsc_dir }}/logback.xml"
    state: link
    src: "{{ lsc_config_dir }}/logback.xml"
    force: yes

- name: Copy LSC configuration
  template:
    src: "lsc.xml.j2"
    dest: "{{ lsc_dir }}/lsc.xml"
    backup: yes
    force: no
