---
- name: Create directories
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{pam_ssh_dir}}"
    - "{{pam_config_dir}}"

- name: Copy config file
  template:
    src: "{{item.file}}.j2"
    dest: "{{pam_config_dir}}/{{item.file}}"
    mode: "{{item.mode}}"
  with_items:
    - { file: nslcd.conf,      mode: 0644 }
    - { file: pam_websso.json, mode: 0640 }

- name: Copy docker-compose config
  template:
    src: docker-compose.yml.j2
    dest: "{{pam_ssh_dir}}/docker-compose.yml"

- name: install pam_ssh service file
  template:
    src: pam_ssh.service.j2
    dest: /etc/systemd/system/pam_ssh.service
  register: result

- name: reload systemd
  systemd:
    daemon_reload: yes
  when: result.changed

- name: start pam_ssh docker
  systemd:
    name: pam_ssh.service
    state: started
    enabled: yes


