---
- name: Add Elesticsearch key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add Elasticsearch repository
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
    update_cache: yes

- name: Ensure that packages are installed
  apt:
    name: "{{ item }}"
    install_recommends: no
  with_items:
    - openjdk-8-jdk
    - elasticsearch
    - logstash
    - kibana

- name: Ensure Elasticsearch data directory exists
  file: path=/var/elasticsearch state=directory mode=0755 owner=elasticsearch

- name: Copy elasticsearch configuration file
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch/elasticsearch.yml
  notify: restart elasticsearch

- name: list elasticsearch plugins
  command: /usr/share/elasticsearch/bin/elasticsearch-plugin list
  register: elasticsearch_plugins
  changed_when: false

- name: install elasticsearch plugins
  command: "/usr/share/elasticsearch/bin/elasticsearch-plugin install --batch {{item}}"
  when: "item not in elasticsearch_plugins.stdout"
  with_items:
    - ingest-geoip
    - ingest-user-agent


- name: Copy logstash configuration file
  copy:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
  notify: restart logstash

- name: Copy kibana configuration file
  copy:
    src: kibana.yml
    dest: /etc/kibana/kibana.yml
  notify: restart kibana

