---
firewall_v4_incoming:
  - { name: bastion,      src: "{{iprange.bastion}}", dport:  "22", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "80", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "{{idp_test_port}}", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "{{sp_test_port}}", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "{{oidc_test_port}}", proto: tcp }
  - { name: loadbalancer, src: "{{iprange.lb}}",      dport:  "{{google_test_port}}", proto: tcp }
  - { name: vnet,         src: "{{iprange.vm}}",      dport: "22,80,443", proto: tcp }

# TODO: move to role default
# SimpleSAMLphp
simplesaml_download_url: "https://github.com/simplesamlphp/simplesamlphp/releases/download"
simplesaml_version: "1.15.3"
simplesaml_project_dir: "/opt/simplesaml"

simplesaml_oidc_repo_url: https://github.com/SURFscz/simplesamlphp-module-openidconnect.git
simplesaml_oidc_repo_version: master
simplesaml_oidc_src_dir: "{{ simplesaml_project_dir }}/module-oidc"
