---
sudo_groups:
  - sudo_test

environment_name: vm
environment_string: "SCZ VM"
base_domain: "scz-vm.net"

# externally visible!
hostnames:
  proxy:    proxy.{{base_domain}}
  mdq:      mdq.{{base_domain}}
  consent:  cm.{{base_domain}}
  comanage: comanage.{{base_domain}}
  ldap:     ldap.{{base_domain}}
  meta:     meta.{{base_domain}}
  oidc:     oidc-test.{{base_domain}}
  sp:       sp-test.{{base_domain}}
  idp:      idp-test.{{base_domain}}
  google:   google-test.{{base_domain}}
  pam:      pam.{{base_domain}}
  orcid:    orcid-test.{{base_domain}}
  ms:       ms-test.{{base_domain}}

idp_test_port: 81
sp_test_port: 82
oidc_test_port: 83
google_test_port: 84
orcid_test_port: 85
ms_test_port: 86
pam_clients_port: 8087

# COmanage-ldap configuration
comanage_ldap_host: "ldap.vm.scz-vm.net"

# TODO: get rid of hardcoded ports for proxy vhosts
loadbalancer:
  - hostname: "{{hostnames.proxy}}"
    http: true
    backend_hosts: "{{groups['vm-proxy']}}"
    backend_port: 8080
  - hostname: "{{hostnames.mdq}}"
    http: true
    backend_hosts: "{{groups['vm-proxy']}}"
    backend_port: 8081
  - hostname: "{{hostnames.consent}}"
    http: true
    backend_hosts: "{{groups['vm-proxy']}}"
    backend_port: 8082
  - hostname: "{{hostnames.comanage}}"
    http: true
    backend_hosts: "{{groups['vm-comanage']}}"
    backend_port: 80
  - hostname: "{{hostnames.meta}}"
    http: true
    backend_hosts: "{{groups['vm-meta']}}"
    backend_port: 80
  - hostname: "{{hostnames.oidc}}"
    http: true
    backend_hosts: "{{groups['vm-client']}}"
    backend_port: "{{oidc_test_port}}"
  - hostname: "{{hostnames.sp}}"
    http: true
    backend_hosts: "{{groups['vm-client']}}"
    backend_port: "{{sp_test_port}}"
  - hostname: "{{hostnames.idp}}"
    http: true
    backend_hosts: "{{groups['vm-client']}}"
    backend_port: "{{idp_test_port}}"
  - hostname: "{{hostnames.google}}"
    http: true
    backend_hosts: "{{groups['vm-client']}}"
    backend_port: "{{google_test_port}}"
  - hostname: "{{hostnames.orcid}}"
    http: true
    backend_hosts: "{{groups['vm-client']}}"
    backend_port: "{{orcid_test_port}}"
  - hostname: "{{hostnames.ms}}"
    http: true
    backend_hosts: "{{groups['vm-client']}}"
    backend_port: "{{ms_test_port}}"
  - hostname: "{{hostnames.pam}}"
    http: true
    backend_hosts: "{{groups['vm-ldap']}}"
    backend_port: "{{pam_clients_port}}"
  - hostname: "{{hostnames.ldap}}"
    http: false
    frontend_port: 636
    backend_hosts: "{{groups['vm-ldap']}}"
    backend_port: 389

client_ldap_clients:
  - co_name: "Rebel Alliance"
    ldap_o: "Rebel Alliance Client 1"
    password: "{{ test_organization_password }}"
    uid_start: 1000
    gid_start: 1000
  - co_name: "Rebel Alliance"
    ldap_o: "Rebel Alliance Client 2"
    password: "{{ test_organization_password }}"
    uid_start: 4200
    gid_start: 5000
