---
- name: Ensure that packages are installed
  apt:
    name:
      - xalan
      - wget
      - xmlsec1
    state: present

- name: Remove obsolete cron file
  file:
    path: /etc/cron.d/create_metadata
    state: absent

- name: Create project directory
  file: path="{{ metadata_project_dir }}" state=directory mode=0755

- name: Create html directory
  file: path="/var/www/html" state=directory mode=0755

- name: List all xml/xsl files
  find:
    paths: "{{ metadata_project_dir }}"
    patterns:
      - "*.xml"
      - "*.xsl"
  register: oldfiles_glob

- name: Remove old metadata and stylesheet files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items:
    - "{{ oldfiles_glob.files }}"

- name: Copy xsl files in place
  copy: src={{ item }} dest={{ metadata_project_dir }}/{{ item }}
  with_items:
    - idps.xsl
    - nologo.xsl
    - nohide.xsl
    - nosc.xsl

- name: Copy eduGAIN public metadata signing cert
  copy:
    content: "{{ edugain_cert }}"
    dest: "{{ metadata_project_dir }}/edugain.crt"

- name: Copy xsl processing script script in place
  template: src=create_metadata.j2 dest={{ metadata_project_dir }}/create_metadata mode=0755

- name: Copy metadata service files
  template:
    src: "{{item}}.j2"
    dest: "/etc/systemd/system/{{item}}"
  with_items:
    - metadata.service
    - metadata.timer
  notify:
    - enable metadata job

- name: Run the metadata cronjob now
  command: "{{ metadata_project_dir }}/create_metadata"
  args:
    chdir: "{{ metadata_project_dir }}"

- name: Install logos
  copy: src={{item}} dest=/var/www/html/{{item}} owner=www-data group=www-data
  with_items:
    - Light-Bulb_icon_by_Till_Teenck.svg
    - Light-Bulb_icon_by_Till_Teenck_200px.png
    - Light-Bulb_icon_by_Till_Teenck_1000px.png
